import { NextRequest, NextResponse } from "next/server"
import { createClient } from "@supabase/supabase-js"

export const maxDuration = 60

const GH = "https://api.github.com"

function ghHeaders(token: string) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
  }
}

async function ghFetch(url: string, token: string, options?: RequestInit) {
  const res = await fetch(url, { ...options, headers: ghHeaders(token) })
  const json = await res.json()
  if (!res.ok) throw new Error(json.message ?? `GitHub API error ${res.status}`)
  return json
}

async function waitForFork(forkOwner: string, repo: string, branch: string, token: string, retries = 6) {
  for (let i = 0; i < retries; i++) {
    try {
      await ghFetch(`${GH}/repos/${forkOwner}/${repo}/git/ref/heads/${branch}`, token)
      return // fork is ready
    } catch {
      if (i < retries - 1) await new Promise(r => setTimeout(r, 2000))
    }
  }
  throw new Error("Fork is not ready yet — please try again in a moment")
}

export async function POST(req: NextRequest) {
  const { reportId, targetLocale, mergedContent, githubToken } = await req.json() as {
    reportId?: string
    targetLocale?: string
    mergedContent?: string
    githubToken?: string
  }

  if (!reportId || !targetLocale || !mergedContent || !githubToken) {
    return NextResponse.json({ error: "Missing required fields" }, { status: 400 })
  }

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  )
  const { data: row } = await supabase
    .from("reports")
    .select("repo_owner, repo_name, report")
    .eq("id", reportId)
    .single()

  if (!row) return NextResponse.json({ error: "Report not found" }, { status: 404 })

  const owner: string = row.repo_owner
  const repo: string = row.repo_name
  const branch: string = row.report.repoInfo.branch
  const files: Record<string, string[]> = row.report.localeGroup?.files ?? {}
  const filePaths = files[targetLocale]

  if (!filePaths?.length) {
    return NextResponse.json({ error: "Re-scan this repo to enable PR creation" }, { status: 400 })
  }

  const filePath = filePaths[0]!
  const newBranch = `i18n-doctor/fix-${targetLocale}-${Date.now()}`

  try {
    // Get the authenticated user's GitHub login
    const me = await ghFetch(`${GH}/user`, githubToken)
    const myLogin: string = me.login
    const isOwner = myLogin.toLowerCase() === owner.toLowerCase()

    let targetOwner = owner

    if (!isOwner) {
      // Fork the repo (idempotent — returns existing fork if already forked)
      await ghFetch(`${GH}/repos/${owner}/${repo}/forks`, githubToken, { method: "POST" })
      targetOwner = myLogin
      // Wait for fork to be available
      await waitForFork(targetOwner, repo, branch, githubToken)
    }

    // Get base branch SHA from our target repo (own repo or fork)
    const baseRef = await ghFetch(`${GH}/repos/${targetOwner}/${repo}/git/ref/heads/${branch}`, githubToken)
    const baseSha: string = baseRef.object.sha

    // Create new branch on target repo
    await ghFetch(`${GH}/repos/${targetOwner}/${repo}/git/refs`, githubToken, {
      method: "POST",
      body: JSON.stringify({ ref: `refs/heads/${newBranch}`, sha: baseSha }),
    })

    // Get existing file SHA if file exists (needed for update vs create)
    let existingFileSha: string | undefined
    try {
      const existing = await ghFetch(
        `${GH}/repos/${targetOwner}/${repo}/contents/${filePath}?ref=${newBranch}`,
        githubToken,
      )
      existingFileSha = existing.sha
    } catch { /* file doesn't exist yet — will create it */ }

    // Commit the fixed file
    const contentBase64 = Buffer.from(mergedContent).toString("base64")
    await ghFetch(`${GH}/repos/${targetOwner}/${repo}/contents/${filePath}`, githubToken, {
      method: "PUT",
      body: JSON.stringify({
        message: `fix(i18n): translate ${targetLocale} locale via i18n.doctor`,
        content: contentBase64,
        branch: newBranch,
        ...(existingFileSha ? { sha: existingFileSha } : {}),
      }),
    })

    // Create pull request (always against the original repo)
    const pr = await ghFetch(`${GH}/repos/${owner}/${repo}/pulls`, githubToken, {
      method: "POST",
      body: JSON.stringify({
        title: `fix(i18n): translate \`${targetLocale}\` locale via i18n-doctor`,
        body: `## i18n.doctor — Translation Fix\n\nThis PR was auto-generated by [i18n-doctor](https://i18n-doctor.vercel.app).\n\n- **Locale:** \`${targetLocale}\`\n- **File:** \`${filePath}\`\n\nMissing and untranslated keys were filled using [Lingo.dev](https://lingo.dev).`,
        head: isOwner ? newBranch : `${myLogin}:${newBranch}`,
        base: branch,
        draft: true,
      }),
    })

    return NextResponse.json({ prUrl: pr.html_url })
  } catch (e) {
    const message = e instanceof Error ? e.message : "Failed to create PR"
    return NextResponse.json({ error: message }, { status: 400 })
  }
}
